### ISSUE TITLE
Can't build wheels for panda

### ISSUE THREAD

**Issue by Monsieur-Hash** [pawlaczyk/sarenka#51] opened 2021-05-14 09:32 UTC
Hi, I try several things to resolve this issue but I can't find any tricks that work.
Every time I try to install the requirements I returne me "ERROR: Could not build wheels for pandas which use PEP 517 and cannot be installed directly  "
I try to not use pep but nothing work.
Thanks in advance.

**Comment by pawlaczyk** [comment] 2021-05-14 19:27
Hi,
I will try to fix when I reproduce an environment and  this issue.

Could you tell me more about the environment?
Is it while you installing requirements? 
On which system? - or it's a docker?
You are using 'master' branch?
Which python version you use?

**Comment by Monsieur-Hash** [comment] 2021-05-15 13:59
Hi, I use Kali 2021.1 in virtualbox.
Its when I install requirements.
I try both master branch and regular, same error.
Python 2.7.18
Z Uszanowaniem :)

**Comment by pawlaczyk** [comment] 2021-05-15 14:28
Hi,
Python 2.X is not supported! 
Python 3.8  is the oldest Python tested and supported version.

Try to create virtualenv with python 3.8 (or newest) and install packages in it.
If it doesn't help let me know.

Pozdrawiam :>

**Comment by Monsieur-Hash** [comment] 2021-05-16 18:38
Hello again, I try to install packages in a virtualenv with python 3.9.2 and the same error keep happening.

**Comment by pawlaczyk** [comment] 2021-05-17 19:20
Hi, 
I was able to reproduce the error. The easiest solution is to install pandas==1.2.4, which I have already added to the requirements.txt file. I’ve tested library and application installation on Kali 2021.1 and Windows 10. 
Please install new requirements or just pip install pandas===1.2.4. 

The problem with packages installation connects with your environment, not an application.
Being not able to fix a common problem with packages and thinking that is application responsibly, gives me the feeling that you’re not ready for almost always tricky Kali distro.

Please try easier, with larger community OS like Debian, Ubuntu. 
Web apps work on higher levels of abstraction. There is a lot of change that you don’t have to force yourself to use Kali to install a specific app. For example, sarenka also works on Ubuntu.

Next time you can comment with the # troublesome line of requirements.txt and try to install the library standalone with pip (not pip install -r). Keep in mind there is usually backward compatibility, and you can always check a slightly newest package version.

Take care :)


I’m closing this issue because it is not connected with the application itself.

**Closed by pawlaczyk** 2021-05-17 19:20 UTC

**Comment by Monsieur-Hash** [comment] 2021-05-21 19:35
Hi, I finnaly succed to run it. :)
Im a student you are probably right for kali its too soon.
Anyway thanks for your halp and for sarenka.
Have a good day .

**Comment by pawlaczyk** [comment] 2021-05-22 10:59
Hi, 
I’m glad you did it!

If you felt bad after my previous answer, I’m really sorry. I didn’t mean to offend you. 
I just saw you act as my younger self :)

Please master some basic Linux skills (commands, filesystem, bash), the book “Podstawy Systemu Linux dla Hakerów” Bryson Payne ISBN-978-83-01-20887-5 should be nice for starting.

Greets
